// Mocks generated by Mockito 5.4.6 from annotations
// in miniature_paint_finder/test/widgets/screens/wishlist_screen.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:miniature_paint_finder/models/most_used_paint.dart' as _i5;
import 'package:miniature_paint_finder/services/palette_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [PaletteService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPaletteService extends _i1.Mock implements _i2.PaletteService {
  MockPaletteService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i3.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i4.Future<Map<String, dynamic>> uploadImage(
    String? imagePath,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#uploadImage, [imagePath, token]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> createPalette(String? name, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#createPalette, [name, token]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getImagePicks(
    String? imageId,
    String? token,
    List<Map<String, dynamic>>? colorData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getImagePicks, [imageId, token, colorData]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<List<Map<String, dynamic>>> getAllPalettesNamesAndIds(
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllPalettesNamesAndIds, [token]),
            returnValue: _i4.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i4.Future<List<Map<String, dynamic>>>);

  @override
  _i4.Future<void> addPaintsToPalette(
    String? paletteId,
    List<Map<String, dynamic>>? paints,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addPaintsToPalette, [paletteId, paints, token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> addPaintToPaletteById(
    String? paletteName,
    String? userId,
    String? paintId,
    String? brandId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#addPaintToPaletteById, [
              paletteName,
              userId,
              paintId,
              brandId,
            ]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> deletePalette(
    String? paletteId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deletePalette, [paletteId, token]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> removePaintFromPalette(
    String? paletteId,
    String? paintId,
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removePaintFromPalette, [
              paletteId,
              paintId,
              token,
            ]),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<List<_i5.MostUsedPaint>> getMostUsedPaints(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getMostUsedPaints, [token]),
            returnValue: _i4.Future<List<_i5.MostUsedPaint>>.value(
              <_i5.MostUsedPaint>[],
            ),
          )
          as _i4.Future<List<_i5.MostUsedPaint>>);
}
