// Mocks generated by Mockito 5.4.6 from annotations
// in miniature_paint_finder/test/services/inventory_cache_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:miniature_paint_finder/models/paint.dart' as _i5;
import 'package:miniature_paint_finder/models/paint_inventory_item.dart' as _i3;
import 'package:miniature_paint_finder/services/inventory_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [InventoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockInventoryService extends _i1.Mock implements _i2.InventoryService {
  MockInventoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.PaintInventoryItem> get inventory =>
      (super.noSuchMethod(
            Invocation.getter(#inventory),
            returnValue: <_i3.PaintInventoryItem>[],
          )
          as List<_i3.PaintInventoryItem>);

  @override
  int get totalPages =>
      (super.noSuchMethod(Invocation.getter(#totalPages), returnValue: 0)
          as int);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  _i4.Future<void> loadInventory({
    int? limit = 10,
    int? page = 1,
    String? searchQuery,
    bool? onlyInStock,
    String? brand,
    String? category,
    int? minStock,
    int? maxStock,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadInventory, [], {
              #limit: limit,
              #page: page,
              #searchQuery: searchQuery,
              #onlyInStock: onlyInStock,
              #brand: brand,
              #category: category,
              #minStock: minStock,
              #maxStock: maxStock,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getUniqueBrands() =>
      (super.noSuchMethod(
            Invocation.method(#getUniqueBrands, []),
            returnValue: _i4.Future<List<String>>.value(<String>[]),
          )
          as _i4.Future<List<String>>);

  @override
  List<String> getUniqueCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getUniqueCategories, []),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  int getMaxStockLevel() =>
      (super.noSuchMethod(
            Invocation.method(#getMaxStockLevel, []),
            returnValue: 0,
          )
          as int);

  @override
  bool updateStock(String? paintId, int? newStock) =>
      (super.noSuchMethod(
            Invocation.method(#updateStock, [paintId, newStock]),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<bool> updateStockFromApi(String? inventoryId, int? newStock) =>
      (super.noSuchMethod(
            Invocation.method(#updateStockFromApi, [inventoryId, newStock]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> updateInventoryRecord(
    String? inventoryId,
    int? quantity,
    String? notes,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateInventoryRecord, [
              inventoryId,
              quantity,
              notes,
            ]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  bool updateNotes(String? paintId, String? notes) =>
      (super.noSuchMethod(
            Invocation.method(#updateNotes, [paintId, notes]),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<bool> updateNotesFromApi(String? inventoryId, String? notes) =>
      (super.noSuchMethod(
            Invocation.method(#updateNotesFromApi, [inventoryId, notes]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  bool addPaintToInventory(
    _i5.Paint? paint, {
    int? stock = 1,
    String? notes = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addPaintToInventory,
              [paint],
              {#stock: stock, #notes: notes},
            ),
            returnValue: false,
          )
          as bool);

  @override
  bool removePaintFromInventory(String? paintId) =>
      (super.noSuchMethod(
            Invocation.method(#removePaintFromInventory, [paintId]),
            returnValue: false,
          )
          as bool);

  @override
  List<_i3.PaintInventoryItem> filterInventory({
    String? searchQuery = '',
    bool? onlyInStock = false,
    String? brand,
    String? category,
    int? minStock = 0,
    int? maxStock = 999,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#filterInventory, [], {
              #searchQuery: searchQuery,
              #onlyInStock: onlyInStock,
              #brand: brand,
              #category: category,
              #minStock: minStock,
              #maxStock: maxStock,
            }),
            returnValue: <_i3.PaintInventoryItem>[],
          )
          as List<_i3.PaintInventoryItem>);

  @override
  List<_i3.PaintInventoryItem> sortInventory(
    List<_i3.PaintInventoryItem>? items,
    String? sortColumn,
    bool? ascending,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sortInventory, [items, sortColumn, ascending]),
            returnValue: <_i3.PaintInventoryItem>[],
          )
          as List<_i3.PaintInventoryItem>);

  @override
  List<String> getPalettesUsingPaint(String? paintId) =>
      (super.noSuchMethod(
            Invocation.method(#getPalettesUsingPaint, [paintId]),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  _i4.Future<bool> addInventoryRecord({
    required String? brandId,
    required String? paintId,
    required int? quantity,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addInventoryRecord, [], {
              #brandId: brandId,
              #paintId: paintId,
              #quantity: quantity,
              #notes: notes,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<String?> addInventoryRecordReturningId({
    required String? brandId,
    required String? paintId,
    required int? quantity,
    String? notes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addInventoryRecordReturningId, [], {
              #brandId: brandId,
              #paintId: paintId,
              #quantity: quantity,
              #notes: notes,
            }),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<Map<String, dynamic>> loadInventoryFromApi({
    int? limit = 10,
    int? page = 1,
    String? searchQuery,
    bool? onlyInStock,
    String? brand,
    String? category,
    int? minStock,
    int? maxStock,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#loadInventoryFromApi, [], {
              #limit: limit,
              #page: page,
              #searchQuery: searchQuery,
              #onlyInStock: onlyInStock,
              #brand: brand,
              #category: category,
              #minStock: minStock,
              #maxStock: maxStock,
            }),
            returnValue: _i4.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<bool> deleteInventoryRecord(String? inventoryId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteInventoryRecord, [inventoryId]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
